
# Map Details
map_size: 32
map_resolution: 1.0
coverage_size: 10.0

obstacles:
    - {id: 3, x: 5,  y: 5,  width: 3.0, length: 7.0, height: 20.0}
    - {id: 2, x: -5,  y: 5,  width: 2.0, length: 6.0, height: 20.0}
    - {id: 1, x: -5,  y: -5,  width: 1.0, length: 1.0, height: 20.0}


# Location of the basestation in the map (Will be used to spawn basestation and robots around it)
basestation_x: 0
basestation_y: 0
basestation_z: 0

# Robot parameters
vehicle_num: 1
nodes_per_robot: 10.0

# Sim Parameters
del_t: 0.25  # timestep between sim updates
waypt_threshold: 3.0