
# Location of the basestation in the map (Will be used to spawn basestation and robots around it)
basestation_x: 0
basestation_y: 0
basestation_z: 0

vehicle_num: 10

del_t: 0.25  # timestep between sim updates

waypt_threshold: 3.0
nodes_per_robot: 10.0


obstacles:
    - {id: 3, x: 15,  y: 15,  width: 2.0, length: 6.0, height: 20.0}
    - {id: 2, x: -15,  y: 15,  width: 2.0, length: 6.0, height: 20.0}
    - {id: 1, x: -15,  y: -15,  width: 1.0, length: 6.0, height: 20.0}
